Update README.md
Kaholo/kaholo-plugin-amazon-ec2 pull request #21
Opened 2022-02-15 14:25 UTC by arispen

add modify instance attribute method to readme

2022-02-15 14:27 UTC, kdebowski-kaholo requested changes

2022-02-15 14:27 UTC, kdebowski-kaholo commented on README.md
> +2. Secret Key - This is a paramer taken from the vault to access AWS
typo

2022-02-15 14:27 UTC, kdebowski-kaholo commented on README.md
> +4. Instance IDs - Instance IDs of all instances you want to modify. Accecpts either a string with one or multiple instance IDs, each seperated with a new line,
"Accecpts" typo

2022-02-15 14:27 UTC, kdebowski-kaholo commented on README.md
> +6. attributeValue (string) specify the new value of an attrubute
"attrubute" typo

2022-03-23 05:56 UTC, kenskyfish approved these changes
Not sure if this doco is all good, but merging only to provide base for further refinement of README.md

2022-03-23 05:57 UTC, kenskyfish submitted a review, later dismissed
Sure thing

2022-03-23 09:16 UTC, kdebowski-kaholo approved these changes

2022-03-23 09:17 UTC, merged